config/routes.rb
Rails.application.routes.draw do
  resources :pokemons
  resources :movies
  resources :products
  resources :items
  resources :posts, only: :index
  root "products#index"
  get 'fetch_poke' => 'items#fetch_poke'
  get 'test' => 'items#test'
  get 'lp' => 'items#lp'
  get 'mtest' => 'movies#test'
  get 'mlp' => 'movies#lp'
  get 'mlpf' => 'movies#lpf'
end

app/models/item.rb
class Item < ApplicationRecord
  enum access: {
    draft: 'draft',
    published: 'published',
    passcode_protected: 'passcode_protected',
    poke: 'poke'
  }
  validates :body, presence: true
  #validates :access, presence: true
  #validates :pass, presence: true, if: :passcode_protected?
end

app/controllers/items_controller.rb
#Items_Controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

require 'uri'
require 'net/http'

def lp
  # Your logic to fetch data for the partial
  @items = Item.find(1)
  #render partial: 'items/partial', locals: { items: @items }
  render turbo_stream: turbo_stream.append('partial_frame', partial: 'z', locals: { item: @items})
end

def lp
  # Your logic to fetch data for the partial
  @items = Item.find(1)
  #render partial: 'items/partial', locals: { items: @items }
render turbo_stream: turbo_stream.append('partial_frame', partial: 'lf', locals: { item: @items})
end

def fetch_poke(xxx)
  puts xxx
  uri = URI('https://pokeapi.co/api/v2/pokemon?limit=3')
  response = Net::HTTP.get_response(uri)

  if response.is_a?(Net::HTTPSuccess)
    @pokemon_data = JSON.parse(response.body)
    @pokemon_data_which = @pokemon_data["results"][xxx]["name"]
    #session[:pd] = @pokemon_data
    flash[:success] = 'Pokemon successfully loaded!'
  else
    flash[:error] = 'Failed to load Pokemon data!'
  end
  #render turbo_stream: turbo_stream.append('tst', partial: 'poke_names', locals: { pokemon_data: @pokemon_data, item: @item})
  #render :new
end


def test
  @time = Time.now
  @items = Item.all
  @itemn = Item.new
end

  # GET /items or /items.json
  def index
    @items = Item.all
    #flash[:notice]='My Notice'
    #session[:current_item] = @items[1][:name]
  end

  # GET /items/1 or /items/1.json
  def show
    session[:last_item] = Item.find(params[:id])
    session[:last_item_name] = Item.find(params[:id])
    @alla = Item.pluck('body')
  end

  # GET /items/new
  def new
    if params["zomg"]
      @zomg = params[:zomg].to_i
    else
      #@zomg = 2
  end
    puts 'zomg', @zomg  
    #params[:zz]='hi'
    @item = Item.new item_params
    #ItemsController.dispatch(:fetch_poke, request, response)
    puts params[:item].inspect
    p params[:item][:body].to_i if params[:item]
    if params["item"]
      p "fetch_poke #{params[:zomg].inspect}"
      p params[:item][:body].to_i
      #fetch_poke(params[:item][:name].to_i) if params["item"]["access"] == 'poke'
      fetch_poke(params[:item][:zomg].to_i) if params["item"]["access"] == 'poke'
      #debugger
    end
    #fetch_poke if item.poke?
    puts params[:zomg].inspect
    #fetch_poke if params[:fetch_pokemon] == "true" && @item.passcode_protected? # Fetch Pokémon data if item is passcode protected and fetch_pokemon parameter is true    set_default_password if @item.passcode_protected? # Set default password

    #params[:aa]="aa" if @pokemon_data
    #@item[:name] = session[:last_item]["name"]
    #puts session[:last_item][:name].inspect
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)
    @items = Item.all

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy!

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_default_password
  # Set the password to "bulbasaur" or @poke_data["results][0]["name"]
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.fetch(:item, {}).permit(:name, :body, :access, :pass)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<!-- items/_form.html.erb -->
<%= form_with(model: item, class: "contents") do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <%= form.button "Validate", formaction: new_item_path, formmethod: :get, data: { turbo_frame: :pass_field, formelement_target: "submitbtn" } %>
  <%# <div class="my-5"> %>
  <div data-controller="formelement">
    <%= form.button "Validate", formaction: new_item_path, formmethod: :get, data: { turbo_frame: :pass_field, formelement_target: "submitbtn" } %>

    <div class="my-5">
      <%= form.label :name %>
      <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <%#DOESNT WORK%>
    <%= form.label :zomg %>
    <%= form.text_field :zomg, value: @zomg %>

    <div class="my-5">
      <%= form.label :body %>
      <%= form.text_area :body, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  

  <div class="my-5">
    <%= form.label :access, style: "display: block" %>
    <%= form.select :access, Item.accesses, {include_blank: true}, { data: { action: "change->formelement#remotesubmit"}} %>
    <%#= form.select :access, Post.accesses, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  </div>

<div id="tst">

</div>

  <%= item.passcode_protected? %>
<%= turbo_frame_tag :pass_field do %>
  <% if item.passcode_protected? || item.poke? %>
    <% if @pokemon_data && @pokemon_data["results"] && @pokemon_data["results"].any?  && item.poke? %>
      <%# pokemon_name = @pokemon_data["results"][1]["name"] %>
      <% pokemon_name = @pokemon_data_which %>
      <% item.pass = pokemon_name %>
      <%= turbo_stream.update "tst", "Pass set to: #{pokemon_name}" %>
      <%= turbo_stream.update "tst", params.inspect +   params[:item].inspect + params[:item]["body"].inspect %>
      <%#= turbo_stream.update "tst", "params"  %>
    <% else %>
      <%= turbo_stream.update "tst", params["item"].inspect %>
      <% item.pass = '' %>
    <% end %>
    <div class="my-5">
      <%= form.label :pass %>
      <%= form.text_field :pass, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", value: @item&.pass %>
    </div>
  <% end %>
<% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

  <%# <form action="/fetch_poke" method="get">
    <input name="zz" type="text">
    <button type="submit">Search</button>
  </form> %>

    <form action="/items/new" >
    <input name="zz" type="text">
    <button type="submit">Search</button>
  </form>

  <%= form_with(url: new_item_path, method: :get) do %>
  <%= text_field_tag :zomg, @zomg %>
  <%= submit_tag "Change @zomg" %>
<% end %>

<%= turbo_frame_tag 'zomg_form' do %>
  <%= form_with(url: new_item_path, method: :get, id: 'zomg-form') do %>
    <%= text_field_tag :zomg, @zomg %>
    <%= submit_tag "Change @zomg", data: { turbo_frame: 'zomg_form' } %>
  <% end %>
<% end %>

@zomg : <%= @zomg %> <%= @zomg.class %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">


<%= params.inspect %>
<%= params[:id] %>
<%= params[:controller] %>
<%= params[:action] %>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= item.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Body:</strong>
    <%= item.body %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Access:</strong>
    <%= item.access %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Pass:</strong>
    <%= item.pass %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this item", item, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this item", edit_item_path(item), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/items/_poke_names.html.erb
<!-- app/views/pokemon/_pokemon_names.html.erb -->
<%= @item.inspect %>
<%= @pokemon_data['results'][0]['name'].inspect %>
<%#= turbo_stream.update "tst", @item.pass = @pokemon_data['results'][0]['name'].inspect  %>
<% @pokemon_data['results'].each do |poke| %>
  <p><%= poke['name'].capitalize %></p>
<% end %>

app/views/items/_z.html.erb
aa
<%= item.inspect %>

app/views/items/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing item</h1>

  <%= render "form", item: @item %>

  <%= link_to "Show this item", @item, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to items", items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/items/index.html.erb
<script>
  var jk = '<%= Item.accesses %>'
</script>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>


<a href="#" onclick="this.style.backgroundColor='#990000'">Paint it red</a>
<a href="#" onclick="this.style.backgroundColor='#009900';this.style.color='#FFFFFF';">Paint it green</a>
Last Item: <%= session[:last_item].inspect %>
<%#= session[:current_item] %>
Items.find(1)<%= @items[0].inspect %>
Params[ALL]: 
  <%= params.inspect%> <br>
  Params[:controller]: 
  <%= params[:controller].inspect %> <br>
  Params[:action]: 
  <%= params[:action].inspect %> <br>
    Params[q]:
  <%= params[:q].inspect %> <br><br>

    Params[myparam]:
  <%= params[:myparam].inspect %> <br>
  <%= params %><br>
  <form action="/items">
    <input name="myparam" type="text">
    <button type="submit">Search</button>
  </form>


  par book<%= params[:book] %> <br>
  par book<%= params[:book] %> <br>
<%# form_for(@book) with a few fields generates something like this %>
<form action="/items">
  <input type="text" name="book[title]" id="book_title">
  <input type="text" name="book[author]" id="book_author">
  <input type="text" name="book[cover]" id="book_cover">

  <select name="book[language]" id="book_language">
    <option value="English">English</option>
    <option value="Spanish">Spanish</option>
    <option value="French">French</option>
  </select>

  <button type="submit">Create</button>
</form>
<br>
  param :item <%= params[:item].inspect %><br>
  param :item <%= params[:item] %><br>
<%# form_for(@book) with a few fields generates something like this %>
<form action="/items" method="post">
  <input type="text" name="item[name]" id="item_name">
  <input type="text" name="item[body]" id="item_body">

  <select name="item[access]" id="item_accss">
    <option value="draft">English</option>
    <option value="Spanish">Spanish</option>
    <option value="French">French</option>
  </select>

  <button type="submit">Create</button>
</form>



  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Items</h1>
    <%= link_to "New item", new_item_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="items" class="min-w-full">
    <%= render @items %>
  </div>
</div>

app/views/items/new.html.erb
Params[ALL]: 
  <%= params.inspect%> <br>
  Params[:controller]: 
  <%= params[:item].inspect %> <br>

    <form action="/items/new">
    <input name="zz" type="text">
    <button type="submit">Search</button>
  </form>

<div class="mx-auto md:w-2/3 w-full">
<% Item.accesses.keys.each do |zz| %>
  <%= zz.inspect %>
<% end %>

<div class="pokemonList"></div>

  att: <%= Item.find(1).attributes.keys[3] %> <br>
    att: <%= Item.accesses %> <br>
  <%= @item.inspect %>
  <%= Item.inspect %>
  
  <h1 class="font-bold text-4xl">New item</h1>

  <%= render "form", item: @item %>

  <%= link_to "Back to items", items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/items/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <%#= session.inspect %> <br>
    alla:<%= @alla[1].inspect %> <br>
    <% @alla.each do |allas| %>
      <%#= link_to '', path %>
      <%= allas.inspect %>
    <% end %>
      
    <%= session[:last_item.inspect] %>
    <%#= session[:current_item] %>

    <%= render @item %>

    <%= link_to "Edit this item", edit_item_path(@item), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this item", item_path(@item), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to items", items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/items/test.html.erb
<!--
h1 {
  text-align: center;
  font-size: 2em;
  margin: 20px 0;
}

button {
  display: block;
  margin: 20px auto;
  padding: 10px 20px;
  font-size: 1.2em;
  border-radius: 5px;
  border: none;
  background-color: #00bcd4;
  color: white;
}


<h1 data-turbo-frame>The current time is: <%= @time %></h1>

<%= turbo_frame_tag do %>
  <%= button_to "Refresh Time", test_path, method: :get, data: { turbo: "replace" } %>
<% end %>


<div data-controller="pokemon"></div>
-->

<div data-controller="pokemon">
  <!-- Button to trigger fetch action -->
  <button data-action="click->pokemon#fetchPokemonData" data-target="pokemon.submitBtn">Fetch Pokemon</button>

  <!-- Container to display fetched data -->
  <div data-target="pokemon.output"></div>
</div>




<turbo-frame id="messages">

</turbo-frame>

<%= turbo_stream.update "messages", @items[2]["name"] %> 

<%= turbo_frame_tag 'partial_frame' do %>
  <!-- This content will be replaced by the partial -->
<% end %>

<%= link_to 'lp', lp_path, data: { turbo_frame: :partial_framezz }%> <%#  %>
<!-- app/views/posts/show.html.erb -->
<%= button_to 'Load Partial', lp_path, method: :post, remote: true %>







<!-- app/views/items/test.html.erb 
<div data-controller="pokemon">
  <button data-action="click->pokemon#fetchPokemon">Fetch Pokemon</button>
  <div class="pokemon-list"></div>
</div>
-->

<!-- app/views/items/test.html.erb 
<div data-controller="pokemon">
  Button to fetch Pokemon 
  <button data-action="click->pokemon#fetchPokemon">Fetch Pokemon</button>
  Container for fetched data 
  <div class="pokemon-list"></div>
</div>
-->