config/routes.rb
Rails.application.routes.draw do
  resources :pokemons
  resources :movies
  resources :products
  resources :items
  resources :posts, only: :index
  root "products#index"
  get 'fetch_poke' => 'items#fetch_poke'
  get 'test' => 'items#test'
  get 'lp' => 'items#lp'
  get 'mtest' => 'movies#test'
  get 'mlp' => 'movies#lp'
  get 'mlpf' => 'movies#lpf'
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  attribute :access, :string
  attribute :sub_access, :string
  #attribute :sub_accessx, :string
  #enum sub_access: {}, _suffix: true
  
  enum access: {
    draft: 'draft',
    published: 'published',
    passcode_protected: 'passcode_protected',
    poke: 'poke'
  }

  enum sub_access: {
    bulbasaur: 'bulbasaur'
  }, _suffix: true

  # if params[:fetchpokemon]
  #   def self.define_pokemon_enum(names)
  #     enum sub_accessx: names.map { |name| [name.to_sym, name] }.to_h, _suffix: true
  #   end
  # end

end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: %i[ show edit update destroy ]

require 'uri'
require 'net/http'

  # GET /pokemons or /pokemons.json
  def index
    @pokemons = Pokemon.all
  end

  # GET /pokemons/1 or /pokemons/1.json
  def show
  end

  # GET /pokemons/new
def new
  #@data = nil
  @abc=1
  @pokemon = Pokemon.new
  if params[:fetch_pokemon].present?
    @abc+=1
    fetchpokemon(@pokemon) 
    p @first_pokemon_name.inspect
    p @data["results"][0].inspect
  end
end

def fetchpokemon(pokemon)
  # Make HTTP request to fetch Pokémon data
  url = URI("https://pokeapi.co/api/v2/pokemon?limit=7")
  
  response = Net::HTTP.get(url)
  @data = JSON.parse(response)

  # Extract the name of the first Pokémon from the data
  @first_pokemon_name = @data["results"][params[:fetch_pokemon].to_i]["name"]
  @sel_poke = @data["results"][params[:fetch_pokemon].to_i]

  # Set the attributes of the pokemon to the name of the first Pokémon
  pokemon.name = @first_pokemon_name
  puts params[:fetch_pokemon].to_i.class.inspect

  # Fetch Pokemon names and store them in `pokemon_names` array
p 'each'
pokemon_names = @data["results"].map { |result| result["name"] }
#p pokemon_names

#INDIVIDUAL POKEMON DATA FETCHING
url = URI("https://pokeapi.co/api/v2/pokemon/#{params[:fetch_pokemon].to_i}/")
  
response = Net::HTTP.get(url)
@dataz = JSON.parse(response)

# Dynamically define the enum using the fetched Pokemon names
#Pokemon.define_pokemon_enum(pokemon_names)


  # Render the form with updated data using Turbo Streams
  #render turbo_stream: turbo_stream.append('partial_frame', partial: 'forma')
end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons or /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to pokemon_url(@pokemon), notice: "Pokemon was successfully created." }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1 or /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to pokemon_url(@pokemon), notice: "Pokemon was successfully updated." }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1 or /pokemons/1.json
  def destroy
    @pokemon.destroy!

    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: "Pokemon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokemon_params
      params.require(:pokemon).permit(:name, :url, :category)
    end
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/pokemons/_form.html.erb
<%= form_with(model: pokemon, class: "contents") do |form| %>
  <% if pokemon.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
        <% pokemon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :url %>
    <%= form.text_field :url, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category %>
    <%= form.text_field :category, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/pokemons/_forma.html.erb
<%= form_with(model: @pokemon, class: "contents") do |form| %>
  <% if @pokemon.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(@pokemon.errors.count, "error") %> prohibited this @pokemon from being saved:</h2>

      <ul>
        <% @pokemon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :url %>
    <%= form.text_field :url, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category %>
    <%= form.text_field :category, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/pokemons/_pokemon.html.erb
<div id="<%= dom_id pokemon %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= pokemon.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Url:</strong>
    <%= pokemon.url %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= pokemon.category %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this pokemon", pokemon, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this pokemon", edit_pokemon_path(pokemon), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/pokemons/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing pokemon</h1>

  <%= render "form", pokemon: @pokemon %>

  <%= link_to "Show this pokemon", @pokemon, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to pokemons", pokemons_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pokemons/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Pokemons</h1>
    <%= link_to "New pokemon", new_pokemon_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="pokemons" class="min-w-full">
    <%= render @pokemons %>
  </div>
</div>

app/views/pokemons/new.html copy 2.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New pokemon</h1>

<%# <meta name="turbo-visit-control" content="reload">

<!-- or -->

<%= turbo_page_requires_reload %> %>



  <%# if @pokemon_data && @pokemon_data["results"] && @pokemon_data["results"].any?  && item.poke? %>
      <%# pokemon_name = @pokemon_data["results"][1]["name"] %>
      <%# pokemon_name = @pokemon_data_which %>
      <%# item.pass = pokemon_name %>
      <%#= turbo_stream.update "tst", "Pass set to: #{pokemon_name}" %>
      
<%= turbo_frame_tag 'gta' do %>
  <!-- This content will be replaced by the partial -->
<% end %>


<%= turbo_frame_tag 'gto' do %>
  <!-- This content will be replaced by the partial -->
  <% if @data %>
    <%#= turbo_stream.update "gta", 'hi' %>
    <%= turbo_stream.update "gto", @pokemon.url = @data["results"][0]["url"] %>
    <%= turbo_stream.append "gto" do %>
      <% @data['results'].each do |result| %>
        Name: <%= result['name'] %><br>
        Url: <%= result['url'] %><br>
        <%= link_to "Set Category", "#", class: "set-category", data: { name: result['name'] }, remote: true, onclick: "document.getElementById('pokemon_category').value = '#{result['name']}'" %><br>
      <% end %>
    <% end %>
  <% end %>
<% end %>





<%= turbo_frame_tag 'gt' do %>
  <!-- This content will be replaced by the partial -->
<% end %>

<%= turbo_frame_tag 'partial_frame' do %>
  <!-- This content will be replaced by the partial -->
<% end %>

    Params[fetch_pokemon]:
  <%= params[:fetch_pokemon].inspect %> <br>
  <%= params %><br>
  <form action="/pokemons/new">
    <input name="fetch_pokemon" type="text">
    <button type="submit">Search</button>
  </form>

  <!-- new.html.erb -->
<%= form_with(url: new_pokemon_path, method: :get) do |form| %>
  <%= form.submit "Fetch Pokémon", name: "fetch_pokemon" %>
<% end %>

<!-- new.html.erb -->
<form action="/pokemons/new" method="get">
  <input type="submit" value="true" name="fetch_pokemon">
</form>

<form action="/pokemons/new" method="get">
  <select name="fetch_pokemon" id="fetch_pokemon">
    <option value="Fetch Pokémon">English</option>
    <option value="Fetch Pokémon">Spanish</option>
    <option value="French">French</option>
  </select>
  <input type="submit">
  </form>


<%= form_with(url: pokemons_path, method: :post) do |form| %>
  <div class="field">
    <%= form.label :access %>
    <%= form.select :access, Pokemon.accesses, prompt: "Select Pokemon Type", id: "pokemon-access" %>
  </div>
  
  <div class="field" id="sub-access" style="display: none;">
    <%= form.label :sub_access %>
    <%= form.select :sub_access, Pokemon.sub_accesses.keys.map { |sub_access| [sub_access.titleize, sub_access] }, prompt: "Select Pokemon Species", id: "pokemon-sub-access" %>
  </div>

  <%= form.submit %>
<% end %>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var accessSelect = document.getElementById("access");
    var subAccessDiv = document.getElementById("sub-access");

    accessSelect.addEventListener("change", function() {
      var selectedAccess = this.value;
      if (selectedAccess === "poke") {
        subAccessDiv.style.display = "block";
        console.log('poke')
      } else {
        subAccessDiv.style.display = "none";
      }
    });
  });
</script>



<%= turbo_stream.update "gt", params.inspect +   params[:pokemons].inspect %>


  <%= render "form", pokemon: @pokemon %>

  <%= link_to "Back to pokemons", pokemons_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pokemons/new.html copy 3 alpine.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New pokemon</h1>

<%# <meta name="turbo-visit-control" content="reload">

<!-- or -->

<%= turbo_page_requires_reload %> %>



  <%# if @pokemon_data && @pokemon_data["results"] && @pokemon_data["results"].any?  && item.poke? %>
      <%# pokemon_name = @pokemon_data["results"][1]["name"] %>
      <%# pokemon_name = @pokemon_data_which %>
      <%# item.pass = pokemon_name %>
      <%#= turbo_stream.update "tst", "Pass set to: #{pokemon_name}" %>
      
<%= turbo_frame_tag 'gta' do %>
  <!-- This content will be replaced by the partial -->
<% end %>


<%= turbo_frame_tag 'gto' do %>
  <!-- This content will be replaced by the partial -->
  <% if @data %>
    <%#= turbo_stream.update "gta", 'hi' %>
    <%= turbo_stream.update "gto", @pokemon.url = @data["results"][0]["url"] %>
    <%= turbo_stream.append "gto" do %>
      <% @data['results'].each do |result| %>
        Name: <%= result['name'] %><br>
        Url: <%= result['url'] %><br>
        <%= link_to "Set Category", "#", class: "set-category", data: { name: result['name'] }, remote: true, onclick: "document.getElementById('pokemon_category').value = '#{result['name']}'" %><br>
      <% end %>
    <% end %>
  <% end %>
<% end %>





<%= turbo_frame_tag 'gt' do %>
  <!-- This content will be replaced by the partial -->
<% end %>

<%= turbo_frame_tag 'partial_frame' do %>
  <!-- This content will be replaced by the partial -->
<% end %>

    Params[fetch_pokemon]:
  <%= params[:fetch_pokemon].inspect %> <br>
  <%= params %><br>
  <form action="/pokemons/new">
    <input name="fetch_pokemon" type="text">
    <button type="submit">Search</button>
  </form>

  <!-- new.html.erb -->
<%= form_with(url: new_pokemon_path, method: :get) do |form| %>
  <%= form.submit "Fetch Pokémon", name: "fetch_pokemon" %>
<% end %>

<!-- new.html.erb -->
<form action="/pokemons/new" method="get">
  <input type="submit" value="true" name="fetch_pokemon">
</form>

<form action="/pokemons/new" method="get">
  <select name="fetch_pokemon" id="fetch_pokemon">
    <option value="Fetch Pokémon">English</option>
    <option value="Fetch Pokémon">Spanish</option>
    <option value="French">French</option>
  </select>
  <input type="submit">
  </form>


<%= form_with(url: pokemons_path, method: :post) do |form| %>
  <div class="field">
    <%= form.label :access %>
    <%= form.select :access, Pokemon.accesses, prompt: "Select Pokemon Type", id: "pokemon-access" %>
  </div>
  
  <div class="field" id="sub-access" style="display: none;">
    <%= form.label :sub_access %>
    <%= form.select :sub_access, Pokemon.sub_accesses.keys.map { |sub_access| [sub_access.titleize, sub_access] }, prompt: "Select Pokemon Species", id: "pokemon-sub-access" %>
  </div>

  <%= form.submit %>
<% end %>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var accessSelect = document.getElementById("access");
    var subAccessDiv = document.getElementById("sub-access");

    accessSelect.addEventListener("change", function() {
      var selectedAccess = this.value;
      if (selectedAccess === "poke") {
        subAccessDiv.style.display = "block";
        console.log('poke')
      } else {
        subAccessDiv.style.display = "none";
      }
    });
  });
</script>



<%= turbo_stream.update "gt", params.inspect +   params[:pokemons].inspect %>


  <%= render "form", pokemon: @pokemon %>

  <%= link_to "Back to pokemons", pokemons_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pokemons/new.html copy.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New pokemon</h1>

<%# <meta name="turbo-visit-control" content="reload">

<!-- or -->

<%= turbo_page_requires_reload %> %>
<%= turbo_frame_tag 'gt' do %>
  <!-- This content will be replaced by the partial -->
<% end %>

<%= turbo_frame_tag 'partial_frame' do %>
  <!-- This content will be replaced by the partial -->
<% end %>

  <!-- new.html.erb -->
<%= form_with(url: new_pokemon_path, method: :get) do |form| %>
  <%= form.submit "Fetch Pokémon", name: "fetch_pokemon" %>
<% end %>

<%= turbo_stream.update "gt", params.inspect +   params[:pokemons].inspect %>


  <%= render "form", pokemon: @pokemon %>

  <%= link_to "Back to pokemons", pokemons_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pokemons/new.html.erb
<script>
  var jsdata = <%= @data.to_json.html_safe %>;
  console.log(jsdata);
</script>

<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New pokemon</h1>

<%# <meta name="turbo-visit-control" content="reload">

<!-- or -->

<%= turbo_page_requires_reload %> %>



  <%# if @pokemon_data && @pokemon_data["results"] && @pokemon_data["results"].any?  && item.poke? %>
      <%# pokemon_name = @pokemon_data["results"][1]["name"] %>
      <%# pokemon_name = @pokemon_data_which %>
      <%# item.pass = pokemon_name %>
      <%#= turbo_stream.update "tst", "Pass set to: #{pokemon_name}" %>
      
<%= turbo_frame_tag 'gta' do %>
  <!-- This content will be replaced by the partial -->
<% end %>


<%= turbo_frame_tag 'gto' do %>
  <!-- This content will be replaced by the partial -->
  <% if @data %>
    <%= @data['results'][0].inspect %>
    <%#= turbo_stream.update "gta", 'hi' %>
    <%= turbo_stream.update "gto", @pokemon.url = @data["results"][0]["url"] %>
    <%= turbo_stream.append "gto" do %>
      <% @data['results'].each do |result| %>
        Name: <%= result['name'] %> <%= result['name'] %> <br>
        Url: <%= result['url'] %><br>
        <%= link_to "Set Category", "#", class: "set-category", data: { name: result['name'] }, remote: true, onclick: "document.getElementById('pokemon_category').value = '#{result['name']}'" %><br>
      <% end %>
    <% end %>
  <% end %>
<% end %>



<%= turbo_frame_tag 'gt' do %>
  <!-- This content will be replaced by the partial -->
<% end %>

<%= turbo_frame_tag 'partial_frame' do %>
  <!-- This content will be replaced by the partial -->
<% end %>

<br>
    Params[] : 
  <%= params.inspect %><br>
    Params[fetch_pokemon] : 
  <%= params[:fetch_pokemon].inspect %> <br>

  <% if @sel_poke%>
  <%= @sel_poke.inspect %>
  <%= @sel_poke['id'] %>
  <% end %>

  <form action="/pokemons/new">
    <input name="fetch_pokemon" type="text">
    <button type="submit">Search</button>
  </form>

  <!-- new.html.erb -->
<%= form_with(url: new_pokemon_path, method: :get) do |form| %>
  <%= form.submit "Fetch Pokémon", name: "fetch_pokemon" %>
<% end %>

<!-- new.html.erb -->
<form action="/pokemons/new" method="get">
  <input type="submit" value="1" name="fetch_pokemon">
</form>

<form action="/pokemons/new" method="get">
  <select name="fetch_pokemon" id="fetch_pokemon">
    <option value="1">Pokemon1</option>
    <option value="2">Pokemon2</option>
    <option value="3">Pokemon2</option>
  </select>
  <input type="submit">
  </form>

  <form action="/pokemons/new" method="get">
  <select name="fetch_pokemon" id="fetch_pokemon">
    <% if @data.present? %>
      
      <% @data['results'].each_with_index do |pokemon, index| %>
        <option value="<%= index %>"><%= pokemon['name'].capitalize %></option>
      <% end %>
    <% else %>
      <option value="">No Pokemon found</option>
    <% end %>
  </select>
  <input type="submit">
</form>

<% @dat = "hi", "man", "bye" %>
<%= @aaaa %>


<%= form_with(url: pokemons_path, method: :post) do |form| %>
  <div class="field">
    <%= form.label :access %>
    <%= form.select :access, Pokemon.accesses, prompt: "Select Pokemon Type", id: "pokemon-access" %>
  </div>
  
  <div class="field" id="sub-access" style="display: none;">
    <%= form.label :sub_access %>
    <% if @data %>
      <%= form.select :sub_access, options_for_select(@data["results"].map { |result| [result["name"].capitalize, result["name"]] }), prompt: "Select Pokemon Species", id: "pokemon-sub-access" %>
    <% else %>
      <%= form.select :sub_access, options_for_select(@dat.map.with_index { |result, index| ["#{result.capitalize} #{index.inspect}", 2] }), prompt: "Select Pokemon Species", id: "pokemon-sub-access" %>
    <% end %>
  </div>

  <%= form.submit %>
<% end %>


<script>
  document.addEventListener("DOMContentLoaded", function() {
    var accessSelect = document.getElementById("access");
    var subAccessDiv = document.getElementById("sub-access");

    accessSelect.addEventListener("change", function() {
      var selectedAccess = this.value;
      if (selectedAccess === "poke") {
        subAccessDiv.style.display = "block";
        console.log('poke')
      } else {
        subAccessDiv.style.display = "none";
      }
    });
  });
</script>

<% if @dataz.present? %>
  <%= @dataz['name'] %>
  <%= @dataz['id'] %>
  <%= @dataz['abilities'] %>
  <img src="<%= @dataz['sprites']['front_default'] %>" alt="">
  <%= @dataz['sprites']['front_default'].inspect %>
<% end%>



<%= turbo_stream.update "gt", params.inspect +   params[:pokemons].inspect %>


  <%= render "form", pokemon: @pokemon %>

  <%= link_to "Back to pokemons", pokemons_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pokemons/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @pokemon %>

    <%= link_to "Edit this pokemon", edit_pokemon_path(@pokemon), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this pokemon", pokemon_path(@pokemon), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to pokemons", pokemons_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>